test:
  image: php:8.0-cli-alpine3.14
  cache:
    paths: [vendor/]
  before_script:
    - apk -q add py3-pip py3-pillow py3-cffi py3-brotli gcc musl-dev python3-dev pango fontconfig-dev font-noto
    - pip3 -q install weasyprint
    - weasyprint --info
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install -qo
  script:
    - ./vendor/bin/testbench package:test --without-tty
