test:
  image: php:8.0-cli-alpine3.14
  cache:
    paths: [vendor/]
  before_script:
    - apk add -q fontconfig-dev gcc gdk-pixbuf-dev harfbuzz-dev jpeg-dev libffi-dev musl-dev pango-dev py3-brotli py3-cffi py3-pillow py3-pip py3-setuptools py3-wheel python3-dev zlib-dev zopfli-dev
    - pip3 -q install WeasyPrint==53.0b2
    - weasyprint --info
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install -qo
  script:
    - ./vendor/bin/testbench package:test --without-tty
