image: php:8

cache:
  paths:
    - vendor/

before_script:
  - apt-get update -yqq
  - apt-get install -yqq build-essential git libffi-dev libgdbm-dev libharfbuzz-dev libjpeg-dev libmcrypt-dev libncurses5-dev libnss3-dev libpango1.0-dev libpng-devlibreadline-dev libssl-dev libzip-dev python3-cffi python3-dev python3-pip python3-setuptools python3-wheel wget zlib1g-dev
  - pango-view --version
  # - docker-php-ext-install gd zip
  # - pip3 install WeasyPrint==53.0b2
  # - weasyprint --info
  # - curl -sS https://getcomposer.org/installer | php
  # - php composer.phar install --optimize-autoloader --prefer-dist

test:
  script:
    - ./vendor/bin/testbench package:test --without-tty
