image: php:8

cache:
  paths:
    - vendor/

before_script:
  - apt update -yqq
  - apt install -yqq build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev wget git libmcrypt-dev python3-dev python3-pip python3-setuptools python3-wheel python3-cffi libpango-1.0-0 libzip-dev
  - python3 --version
  - pango-view --version
  - python3 -m venv venv
  - source venv/bin/activate
  - pip3 install WeasyPrint==53.0b2
  - weasyprint --info
  - docker-php-ext-install gd zip
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install --optimize-autoloader --prefer-dist

test:
  script:
    - ./vendor/bin/testbench package:test --without-tty
